### PR TITLE
Consolidate otel and otelcollector package

### PR DESCRIPTION
**Pull request by seunghyupoh3517**
##### Checklist

- [x] Tested in playground or other setup
- [x] Documentation is changed or added
- [x] Tests and/or benchmarks are included
- [x] Breaking changes

### Description of change

- - -
This change is [Reviewable](https://reviewable.io/reviews/fluxninja/aperture/598)

### CODE REVIEW

**Review by kwapik — CHANGES_REQUESTED** [review]
> Reviewed 1 of 21 files at r1, 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/598)* status: all files reviewed, 3 unresolved discussions (waiting on @seunghyupoh3517)

___
*[`cmd/aperture-agent/agent.go` line 39 at r2](https://reviewable.io/reviews/fluxninja/aperture/598#-NCxxYexCXAcwS07Q1eI:-NCxxYexCXAcwS07Q1eJ:b-h922pr) ([raw file](https://github.com/fluxninja/aperture/blob/7e9e59df89979770852f682f511c9e61aaeffc91/cmd/aperture-agent/agent.go#L39)):*
> ```Go
> 		prometheus.Module(),
> 		k8s.Module(),
> 		agent.AgentOTELComponentAnnotate(),
> ```

This should be renamed to `AgentOTELModule` or sth like this **and** contain `agent.AgentOTELComponents` inside. No need to call those separately,

In such a case, `AgentOTELComponents` might be not-exported.
___
*[`cmd/aperture-controller/controller.go` line 28 at r2](https://reviewable.io/reviews/fluxninja/aperture/598#-NCxxyl2D_E85aDD41ZY:-NCxxyl2D_E85aDD41ZZ:b-ezsbju) ([raw file](https://github.com/fluxninja/aperture/blob/7e9e59df89979770852f682f511c9e61aaeffc91/cmd/aperture-controller/controller.go#L28)):*
> ```Go
> 	app := platform.New(
> 		platform.Config{}.Module(),
> 		controller.ControllerOTELComponentAnnotate(),
> ```

The same for controller. Rename this and put `ControllOTELComponents` inside.
___
*[`pkg/otelcollector/metricsprocessor/config.go` line 4 at r2](https://reviewable.io/reviews/fluxninja/aperture/598#-NCxyYeE2qranJ20bNQ-:-NCxyYeE2qranJ20bNQ0:bbeou92) ([raw file](https://github.com/fluxninja/aperture/blob/7e9e59df89979770852f682f511c9e61aaeffc91/pkg/otelcollector/metricsprocessor/config.go#L4)):*
> ```Go
> 
> import (
> 	"github.com/fluxninja/aperture/pkg/policies/dataplane/iface"
> ```

NIT: Revert this. The ordering was correct.

**Comment by seunghyupoh3517** [comment]
*[`cmd/aperture-agent/agent.go` line 39 at r2](https://reviewable.io/reviews/fluxninja/aperture/598#-NCxxYexCXAcwS07Q1eI:-NCyDwXRAAUyo8biDfGY:b-lwvuvk) ([raw file](https://github.com/fluxninja/aperture/blob/7e9e59df89979770852f682f511c9e61aaeffc91/cmd/aperture-agent/agent.go#L39)):*
<details><summary><i>Previously, kwapik (Krzysztof Kwapisiewicz) wrote…</i></summary><blockquote>

This should be renamed to `AgentOTELModule` or sth like this **and** contain `agent.AgentOTELComponents` inside. No need to call those separately,

In such a case, `AgentOTELComponents` might be not-exported.
</blockquote></details>

For this case, I am having separate calls to avoid another import cycle that will cause - `agent.AgentOTELComponents` cause circular dependency

**Comment by seunghyupoh3517** [comment]
*[`cmd/aperture-agent/agent.go` line 39 at r2](https://reviewable.io/reviews/fluxninja/aperture/598#-NCxxYexCXAcwS07Q1eI:-NCyEQMc2k-x7pneTSm9:b-357fis) ([raw file](https://github.com/fluxninja/aperture/blob/7e9e59df89979770852f682f511c9e61aaeffc91/cmd/aperture-agent/agent.go#L39)):*
<details><summary><i>Previously, seunghyupoh3517 (Seunghyup Alex Oh) wrote…</i></summary><blockquote>

For this case, I am having separate calls to avoid another import cycle that will cause - `agent.AgentOTELComponents` cause circular dependency
</blockquote></details>

Would it be unsafe to keep it separate call and explicitly have `AgentOTELComponents` exported as it is?

**Comment by seunghyupoh3517** [comment]
*[`cmd/aperture-controller/controller.go` line 28 at r2](https://reviewable.io/reviews/fluxninja/aperture/598#-NCxxyl2D_E85aDD41ZY:-NCyFMJDAm_wzV4WOQTS:b-9t1vu5) ([raw file](https://github.com/fluxninja/aperture/blob/7e9e59df89979770852f682f511c9e61aaeffc91/cmd/aperture-controller/controller.go#L28)):*
<details><summary><i>Previously, kwapik (Krzysztof Kwapisiewicz) wrote…</i></summary><blockquote>

The same for controller. Rename this and put `ControllOTELComponents` inside.
</blockquote></details>

The same response for the agent regarding putting `ControllOTELComponents` inside -- renamed them to `ModuleForAgentOTEL`, `ModuleForControllerOTEL`

**Review by kwapik — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/598)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @seunghyupoh3517)

___
*[`pkg/otelcollector/metricsprocessor/config.go` line 4 at r2](https://reviewable.io/reviews/fluxninja/aperture/598#-NCxyYeE2qranJ20bNQ-:-NCyQU5X9qs4GhW86lGM:b6hjl8w) ([raw file](https://github.com/fluxninja/aperture/blob/7e9e59df89979770852f682f511c9e61aaeffc91/pkg/otelcollector/metricsprocessor/config.go#L4)):*
<details><summary><i>Previously, seunghyupoh3517 (Seunghyup Alex Oh) wrote…</i></summary><blockquote>

Reverted - but how does it make difference?
</blockquote></details>

Functionally it is exactly the same. It is only about following a convention:
```go
import (
    // Standard libraries

    // 3rd party non-standard libraries

    // local imports
)
```

**Comment by seunghyupoh3517** [comment]
*[`cmd/aperture-agent/agent.go` line 39 at r2](https://reviewable.io/reviews/fluxninja/aperture/598#-NCxxYexCXAcwS07Q1eI:-NCyUOQc3qPj2Lc2b2Ds:bgq0aqq) ([raw file](https://github.com/fluxninja/aperture/blob/7e9e59df89979770852f682f511c9e61aaeffc91/cmd/aperture-agent/agent.go#L39)):*
<details><summary><i>Previously, seunghyupoh3517 (Seunghyup Alex Oh) wrote…</i></summary><blockquote>

Would it be unsafe to keep it separate call and explicitly have `AgentOTELComponents` exported as it is?
</blockquote></details>

My bad -- made OTEL Components module into one single call :) THANKS!

**Comment by seunghyupoh3517** [comment]
*[`pkg/otelcollector/metricsprocessor/config.go` line 4 at r2](https://reviewable.io/reviews/fluxninja/aperture/598#-NCxyYeE2qranJ20bNQ-:-NCyUcMG5h3M4UnyYX1L:b-7n7vd) ([raw file](https://github.com/fluxninja/aperture/blob/7e9e59df89979770852f682f511c9e61aaeffc91/pkg/otelcollector/metricsprocessor/config.go#L4)):*
<details><summary><i>Previously, kwapik (Krzysztof Kwapisiewicz) wrote…</i></summary><blockquote>

Functionally it is exactly the same. It is only about following a convention:
```go
import (
    // Standard libraries

    // 3rd party non-standard libraries

    // local imports
)
```
</blockquote></details>

Ahhh Got it! Thanks! It would be convenient if you have linter for this

**Pull request merged**
