### PR TITLE
Use envoy authz in java sdk

### PR DESCRIPTION
**Pull request by IridiumOxide**
##### Checklist

- [x] Tested in playground or other setup
- [ ] Documentation is changed or added
- [ ] Tests and/or benchmarks are included
- [ ] Breaking changes

- - -
This change is [Reviewable](https://reviewable.io/reviews/fluxninja/aperture/816)

### CODE REVIEW

**Review by krdln — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/816)* status: 0 of 191 files reviewed, 5 unresolved discussions (waiting on @IridiumOxide)

*[a discussion](https://reviewable.io/reviews/fluxninja/aperture/816#-NFJVMel7yVhWXUIYUFP:-NFJVMel7yVhWXUIYUFQ:b-ycqldq) (no related file):*
Make sure you add `traffic-direction: INBOUND` header (you might've missed that due to log sampling in Agent)

___
*[a discussion](https://reviewable.io/reviews/fluxninja/aperture/816#-NFJVrV_DjbTc976xf43:-NFJVrV_DjbTc976xf44:bbs5uwr) (no related file):*
Nit: Please try to hide envoy classes from public API (where possible)

___
___
*[`sdks/aperture-java/src/main/java/com/fluxninja/aperture/armeria/ApertureHTTPClient.java` line 39 at r1](https://reviewable.io/reviews/fluxninja/aperture/816#-NFJVb5W45vJbALjCplz:-NFJVb5W45vJbALjCpm-:bhr9hgd) ([raw file](https://github.com/fluxninja/aperture/blob/742a12793f70c4430f66fb53c3e9b641b0986d69/sdks/aperture-java/src/main/java/com/fluxninja/aperture/armeria/ApertureHTTPClient.java#L39)):*
> ```Java
>         EnvoyAuthzFlow flow = this.apertureSDK.startFlowEnvoyAuthz("", attributes);
> 
>         if (flow.accepted()) {
> ```

Remember to iterate the checkResponse.OkResponse.Headers and add/append headers.
___
*[`sdks/aperture-java/src/main/java/com/fluxninja/aperture/sdk/EnvoyAuthzFlow.java` line 9 at r1](https://reviewable.io/reviews/fluxninja/aperture/816#-NFJUfub8Z2yzVD56tLy:-NFJUfuc5yzoaJYBuSoH:b-erwccr) ([raw file](https://github.com/fluxninja/aperture/blob/742a12793f70c4430f66fb53c3e9b641b0986d69/sdks/aperture-java/src/main/java/com/fluxninja/aperture/sdk/EnvoyAuthzFlow.java#L9)):*
> ```Java
> import static com.fluxninja.aperture.sdk.Constants.*;
> 
> public class EnvoyAuthzFlow {
> ```

Nit: Please rename to TrafficFlow / HttpFlow (as discussed)
___
*[`sdks/aperture-java/src/main/java/com/fluxninja/aperture/sdk/EnvoyAuthzFlow.java` line 48 at r1](https://reviewable.io/reviews/fluxninja/aperture/816#-NFJUorp3GP1p30QkO4Y:-NFJUorp3GP1p30QkO4Z:b-d7esf3) ([raw file](https://github.com/fluxninja/aperture/blob/742a12793f70c4430f66fb53c3e9b641b0986d69/sdks/aperture-java/src/main/java/com/fluxninja/aperture/sdk/EnvoyAuthzFlow.java#L48)):*
> ```Java
>         } catch (com.google.protobuf.InvalidProtocolBufferException e) {
>             throw new ApertureSDKException(e);
>         }
> ```

You need to serialize FlowControl.CheckResponse instead, which should be available in `this.checkResponse.dynamicMetadata['aperture.check_response']` (note: I'll be changing this quite soon, so if you encounter problems with this serialization please wait for my changes)



_Code quote:_
```Java
        String checkResponseJSONBytes;
        try {
            checkResponseJSONBytes = JsonFormat.printer().print(this.checkResponse);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new ApertureSDKException(e);
        }
```

**Comment by tanveergill** [comment]
@krdln, @IridiumOxide,

What’s blocking this change? Please try to take this to completion soon

**Review by IridiumOxide — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/816)* status: 0 of 266 files reviewed, 4 unresolved discussions (waiting on @krdln)

*[a discussion](https://reviewable.io/reviews/fluxninja/aperture/816#-NFJVMel7yVhWXUIYUFP:-NFvX0lo2GUtcSybhLpz:b-896fix) (no related file):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

Make sure you add `traffic-direction: INBOUND` header (you might've missed that due to log sampling in Agent)
</blockquote></details>

Done.

___

**Review by IridiumOxide — COMMENTED** [review]
There are no hard blockers; I've been working on moving the .proto file to root API directory and unifying generated java code, and Michał was testing the envoy-authz-equipped decorators. The change will be merged soon

> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/816#-:-NFvYN9h953iBwuzn6WO:b4vhxxh)* status: 0 of 266 files reviewed, 4 unresolved discussions (waiting on @krdln)

**Review by IridiumOxide — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/816)* status: 0 of 266 files reviewed, 2 unresolved discussions (waiting on @krdln)

___
*[`sdks/aperture-java/src/main/java/com/fluxninja/aperture/sdk/EnvoyAuthzFlow.java` line 48 at r1](https://reviewable.io/reviews/fluxninja/aperture/816#-NFJUorp3GP1p30QkO4Y:-NFvYc3zB6bWGHaAsi5H:b-896fix) ([raw file](https://github.com/fluxninja/aperture/blob/742a12793f70c4430f66fb53c3e9b641b0986d69/sdks/aperture-java/src/main/java/com/fluxninja/aperture/sdk/EnvoyAuthzFlow.java#L48)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

You need to serialize FlowControl.CheckResponse instead, which should be available in `this.checkResponse.dynamicMetadata['aperture.check_response']` (note: I'll be changing this quite soon, so if you encounter problems with this serialization please wait for my changes)
</blockquote></details>

Done.

**Review by krdln — CHANGES_REQUESTED** [review]
> Reviewed 55 of 191 files at r1, 5 of 11 files at r2, 88 of 122 files at r4, 117 of 117 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/816)* status: all files reviewed, 3 unresolved discussions (waiting on @IridiumOxide)

___
*[`sdks/aperture-java/src/main/java/com/fluxninja/aperture/armeria/HttpUtils.java` line 100 at r6](https://reviewable.io/reviews/fluxninja/aperture/816#-NFwwWhGDQAqgrbPfFY5:-NFwwWhGDQAqgrbPfFY6:b4zg9t8) ([raw file](https://github.com/fluxninja/aperture/blob/4be47898f7ad46e4f978b0c3845b98aeec0f4fbb/sdks/aperture-java/src/main/java/com/fluxninja/aperture/armeria/HttpUtils.java#L100)):*
> ```Java
>                 continue;
>             }
>             extractedHeaders.put(headerKey, header.getValue());
> ```

Please lowercase the header names as per https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/attribute_context.proto#envoy-v3-api-field-service-auth-v3-attributecontext-httprequest-headers

(I see you're handling both upper and lowercase of content-length so I assume `RequestHeaders` is not normalized)
___
*[`sdks/aperture-java/src/main/java/com/fluxninja/aperture/armeria/HttpUtils.java` line 107 at r6](https://reviewable.io/reviews/fluxninja/aperture/816#-NFwwuAt1ckjUIjsjL7h:-NFwwuAt1ckjUIjsjL7i:b97b09m) ([raw file](https://github.com/fluxninja/aperture/blob/4be47898f7ad46e4f978b0c3845b98aeec0f4fbb/sdks/aperture-java/src/main/java/com/fluxninja/aperture/armeria/HttpUtils.java#L107)):*
> ```Java
>         } else if (extractedHeaders.containsKey("Content-Length")) {
>             requestSize = Integer.parseInt(extractedHeaders.get("content-length"));
>         }
> ```

Nit: You can use `contentLength()` method :) https://javadoc.io/doc/com.linecorp.armeria/armeria-javadoc/latest/com/linecorp/armeria/common/RequestHeaders.html



_Code quote:_
```Java
        int requestSize = -1;
        if (extractedHeaders.containsKey("content-length")) {
            requestSize = Integer.parseInt(extractedHeaders.get("content-length"));
        } else if (extractedHeaders.containsKey("Content-Length")) {
            requestSize = Integer.parseInt(extractedHeaders.get("content-length"));
        }
```
___
*[`sdks/aperture-java/src/main/java/com/fluxninja/aperture/sdk/TrafficFlow.java` line 32 at r6](https://reviewable.io/reviews/fluxninja/aperture/816#-NFx08sY-F1vfw3DQ9e3:-NFx08sY-F1vfw3DQ9e4:b-7cv1k4) ([raw file](https://github.com/fluxninja/aperture/blob/4be47898f7ad46e4f978b0c3845b98aeec0f4fbb/sdks/aperture-java/src/main/java/com/fluxninja/aperture/sdk/TrafficFlow.java#L32)):*
> ```Java
>             return false;
>         }
>         return this.checkResponse.getStatus().getCode() == Code.OK_VALUE;
> ```

Nit: Usually in protobuf `null` is equivalent to "default" instance and all the generated getters are handling that, eg.:
```java
  @java.lang.Override
  public com.fluxninja.generated.google.rpc.Status getStatus() {
    return status_ == null ? com.fluxninja.generated.google.rpc.Status.getDefaultInstance() : status_;
  }
```
So eg. in this function it should be enough to just
```java
return this.checkResponse.getStatus().getCode() == Code.OK_VALUE;
```



_Code quote:_
```Java
        if (this.checkResponse == null || !this.checkResponse.hasStatus()) {
            return true;
        }
        if (this.checkResponse.hasDeniedResponse()) {
            return false;
        }
        return this.checkResponse.getStatus().getCode() == Code.OK_VALUE;
```

**Review by krdln — APPROVED** [review]
> Reviewed 1 of 121 files at r9.
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/816)* status: 59 of 268 files reviewed, all discussions resolved

**Pull request merged**
