### PR TITLE
Added support for generating rpm packages

### PR DESCRIPTION
**Pull request by hdkshingala**
### Description of change

Added support for generating RPM packages and uploading them to GCP on merge with main.

- - -
This change is [Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1055)

### CODE REVIEW

**Review by sbienkow-ninja — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1055)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hdkshingala)

**Review by sbienkow-ninja — CHANGES_REQUESTED** [review]
Need to also update it to generate RPM on release.

> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1055#-:-NKNSKXOCRT512Wwh8eO:btpqdmi)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hdkshingala)

**Comment by hdkshingala** [comment]
> Need to also update it to generate RPM on release.
> 
> > _[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1055#-:-NKNSKXOCRT512Wwh8eO:btpqdmi)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hdkshingala)

Yes I am adding it in the same PR on opsninja.

**Review by sbienkow-ninja — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1055#-:-NKNVPaC3FO0zQZJsJfW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hdkshingala)

**Pull request merged**
