### PR TITLE
Add service informer

### PR DESCRIPTION
**Pull request by hasit**
##### Checklist

- [x] Tested in playground or other setup
- [x] Screenshot (Grafana) from playground added to PR for 15+ minute run
- [ ] Documentation is changed or added
- [ ] Tests and/or benchmarks are included
- [ ] Breaking changes

### CODE REVIEW

**Comment by harjotgill** [comment]
Let's fix the cluster IP tracking first?

**Comment by hasit** [comment]
@harjotgill [4513da3](https://github.com/fluxninja/aperture/pull/1517/commits/4513da35ecb70f609f9bca6e53f0bc32f59619c2) addresses clusterIP tracking using service informer.

**Comment by harjotgill** [comment]
Can we limit this PR to just the cluster IP?

**Comment by hasit** [comment]
Screenshot from 2023-03-06 09-25-31

**Review by harjotgill — APPROVED** [review]

**Pull request merged**
