### PR TITLE
Create children in status registry with key-value pairs

### PR DESCRIPTION
**Pull request by DariaKunoichi**
### Description of change
Adds provided KV as labels to alerts.
Closes: GH-1147
##### Checklist

- [x] Tested in playground or other setup
- [x] Screenshot (Grafana) from playground added to PR for 15+ minute run
- [ ] Documentation is changed or added
- [x] Tests and/or benchmarks are included
- [x] Breaking changes

- - -
This change is [Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1257)

### CODE REVIEW

**Review by krdln — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1257)* status: all files reviewed, 10 unresolved discussions (waiting on @DariaKunoichi)

___
*[`operator/controllers/utils.go` line 138 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNGmDlb0GQPjG1v3RoS:-NNGmDlb0GQPjG1v3RoT:bm8ugco) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/operator/controllers/utils.go#L138)):*
> ```Go
> 			ProbeHandler: corev1.ProbeHandler{
> 				HTTPGet: &corev1.HTTPGetAction{
> 					Path:   "/v1/status/sub_system/liveness",
> ```

It's weird to see liveness / readiness as subsystems, but I guess that's acceptable :shrug: 
___
*[`operator/controllers/utils.go` line 138 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNGmZ86-xye0PWrwsBc:-NNGmZ86-xye0PWrwsBd:blqbuqr) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/operator/controllers/utils.go#L138)):*
> ```Go
> 			ProbeHandler: corev1.ProbeHandler{
> 				HTTPGet: &corev1.HTTPGetAction{
> 					Path:   "/v1/status/sub_system/liveness",
> ```

Nit  I vote for`sub_system` → `subsystem`, as afaik subsystem is more popular spelling than sub-system.
___
*[`pkg/jobs/job.go` line 28 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNGq20z0azNThgHGM9F:-NNGq20z0azNThgHGM9G:b-s6plz4) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/jobs/job.go#L28)):*
> ```Go
> 	Name() string
> 	// Returns the job function or error if it's not applicable for the implementation
> 	GetJobFunc() (JobCallback, error)
> ```

This function is used only in one place and only to check error conditions in BasicJob creation. Let's add a two-arg constructor to BasicJob instead, as discussed elsewhere.
___
*[`pkg/jobs/job-group.go` line 103 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNGx39v0PN8FO40uVo-:-NNGx39w7LYInsnllYcZ:bqy843y) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/jobs/job-group.go#L103)):*
> ```Go
> 		gwAll = append(gwAll, gw...)
> 	}
> 	reg := registry.Child("jgc", jgc.Name)
> ```

I guess `jgc` is Job Group Constructor. The "Constructor" part is only an internal, FX-related concept though. I'd drop this word, so perhaps simply `jg` or `job_group`?
___
*[`pkg/jobs/job-group.go` line 166 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNGw3de1EzZXNrWxi7B:-NNGw3de1EzZXNrWxi7C:bncsqt7) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/jobs/job-group.go#L166)):*
This path is very weird TBH:

> sub_system/liveness/jg/job_groups/k/v

_and_ from my understanding, `k = "jgc"` and `v = `jgc.Name`. So it's actually

> sub_systems/liveness/jg/job_groups/jgc/\<job group name\>

Can we do simply

> subsystem/liveness/job_group/\<job group name\>

Also, I'm confused why we do call `.Root()` instead of using the previusly-created child-registry, but I guess that's another topic.
___
*[`pkg/notifiers/fx-driver.go` line 154 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNGzYJE8y9m7ED2nDqe:-NNGzYJE8y9m7ED2nDqf:b-y518qn) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/notifiers/fx-driver.go#L154)):*
> ```Go
> // GetKeyNotifier returns a KeyNotifier that will notify the driver of key changes.
> func (fxDriver *FxDriver) GetKeyNotifier(key Key) KeyNotifier {
> 	statusRegistry := fxDriver.StatusRegistry.Child("component_id", key.String())
> ```

I don't think `component_id` applies to every key... This name should be more generic.
___
*[`pkg/policies/flowcontrol/resources/classifier/provide.go` line 74 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNH-8kZ4V7npCDamqac:-NNH-8kZ4V7npCDamqad:bp5bt76) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/policies/flowcontrol/resources/classifier/provide.go#L74)):*
> ```Go
> // ProvideClassificationEngine provides a classifier that loads the rules from config file.
> func ProvideClassificationEngine(in ClassificationEngineIn) (iface.ClassificationEngine, *ClassificationEngine) {
> 	reg := in.Registry.Child("res", "classifiers")
> ```

Nit: Perhaps `"resource"`. I think we're inconsistent in when we make shorcuts and when not. Perhaps always go with full words? Up to you though.
___
*[`pkg/policies/flowcontrol/resources/fluxmeter/flux-meter.go` line 78 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNH-Mg8Dgu4iHI0Sdau:-NNH-Mg8Dgu4iHI0Sdav:b-89a4l7) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/policies/flowcontrol/resources/fluxmeter/flux-meter.go#L78)):*
> ```Go
> 	engineAPI = e
> 
> 	reg := sr.Child("res", "flux_meters")
> ```

Ditto
___
*[`pkg/status/registry.go` line 106 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNH-ZR6Dy9wUGT7TgVO:-NNH-ZR6Dy9wUGT7TgVP:b-rzptxk) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/status/registry.go#L106)):*
> ```Go
> 	defer r.mu.RUnlock()
> 	hash := fmt.Sprintf("%s:%s", key, value)
> 	child, ok := r.children[hash]
> ```

There's no need for this sprintfed-"hash" thing. You can make `struct KV { Key, Value string }` or so, and use this as keys of `children`.
___
*[`pkg/status/registry.go` line 195 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNH-xjt2MT8_CvoGJZM:-NNH-xjt2MT8_CvoGJZN:b-wgvnvd) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/status/registry.go#L195)):*
> ```Go
> 	r.status = groupStatus.Status
> 	for hash, gs := range groupStatus.Groups {
> 		splitHash := strings.Split(hash, ":")
> ```

ditto (having KV struct would let you avoid this string-splitting here)

**Review by krdln — CHANGES_REQUESTED** [review]
In some places these key-value pairs work (eg. Child("policy", policyID)), but in some places these "keys" feels really artifical (eg. Child("circuit", "circuit_signals")). I guess it's good enough though and we can tweak this later.

> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1257#-:-NNH0spm8LcR3xc-GEgF:b-92zynj)* status: all files reviewed, 11 unresolved discussions (waiting on @DariaKunoichi)

___
*[`pkg/status/registry.go` line 82 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNH0fYeCuWfKmbwKPib:-NNH0fYeCuWfKmbwKPic:b-2asvbw) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/status/registry.go#L82)):*
> ```Go
> 	hash := fmt.Sprintf("%s:%s", key, value)
> 	uri := fmt.Sprintf("%s/%s/%s", r.uri, key, value)
> 	labeledAlerter := r.alerter.WithLabels(map[string]string{uriKey: uri, key: value})
> ```

I think we wanted to add `key:value` label to the Child alerter by default.

**Review by DariaKunoichi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1257)* status: all files reviewed, 9 unresolved discussions (waiting on @krdln)

___
*[`operator/controllers/utils.go` line 138 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNGmZ86-xye0PWrwsBc:-NNH2a5i5J0547IG-YlE:b-nggxiw) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/operator/controllers/utils.go#L138)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

Nit  I vote for`sub_system` → `subsystem`, as afaik subsystem is more popular spelling than sub-system.
</blockquote></details>

ok, I like it
___
*[`pkg/jobs/job.go` line 28 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNGq20z0azNThgHGM9F:-NNH2cyV5Cql8LOzGRkK:b21ewak) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/jobs/job.go#L28)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

This function is used only in one place and only to check error conditions in BasicJob creation. Let's add a two-arg constructor to BasicJob instead, as discussed elsewhere.
</blockquote></details>

Ok, I'll see how that will behave in tests
___
*[`pkg/jobs/job-group.go` line 103 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNGx39v0PN8FO40uVo-:-NNH2j3x3Ht1lOM4gf5I:b32wtd) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/jobs/job-group.go#L103)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

I guess `jgc` is Job Group Constructor. The "Constructor" part is only an internal, FX-related concept though. I'd drop this word, so perhaps simply `jg` or `job_group`?
</blockquote></details>

ok
___
*[`pkg/jobs/job-group.go` line 166 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNGw3de1EzZXNrWxi7B:-NNH2qbBAKwnqx4Edoxx:bnadhp7) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/jobs/job-group.go#L166)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

This path is very weird TBH:

> sub_system/liveness/jg/job_groups/k/v

_and_ from my understanding, `k = "jgc"` and `v = `jgc.Name`. So it's actually

> sub_systems/liveness/jg/job_groups/jgc/\<job group name\>

Can we do simply

> subsystem/liveness/job_group/\<job group name\>

Also, I'm confused why we do call `.Root()` instead of using the previusly-created child-registry, but I guess that's another topic.
</blockquote></details>

I'm trying to reproduce the path that whole job group registration process creates - if you want to shorten it I would have to rewrite jobs implementation - not part of this PR
___
*[`pkg/notifiers/fx-driver.go` line 154 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNGzYJE8y9m7ED2nDqe:-NNH36LC7MBZ3oXOHyr_:b-jdutyg) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/notifiers/fx-driver.go#L154)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

I don't think `component_id` applies to every key... This name should be more generic.
</blockquote></details>

ok, so what would you use? ;D
___
*[`pkg/policies/flowcontrol/resources/classifier/provide.go` line 74 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNH-8kZ4V7npCDamqac:-NNH3GIS224lrwZgAqE3:b32wtd) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/policies/flowcontrol/resources/classifier/provide.go#L74)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

Nit: Perhaps `"resource"`. I think we're inconsistent in when we make shorcuts and when not. Perhaps always go with full words? Up to you though.
</blockquote></details>

ok
___
*[`pkg/policies/flowcontrol/resources/fluxmeter/flux-meter.go` line 78 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNH-Mg8Dgu4iHI0Sdau:-NNH3Hh69dcRxSs_JqF2:b-896fix) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/policies/flowcontrol/resources/fluxmeter/flux-meter.go#L78)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[`pkg/status/registry.go` line 82 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNH0fYeCuWfKmbwKPib:-NNH3Kgh0xKZcULUdhYN:bfefnk0) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/status/registry.go#L82)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

I think we wanted to add `key:value` label to the Child alerter by default.
</blockquote></details>

so what's the problem?
___
*[`pkg/status/registry.go` line 106 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNH-ZR6Dy9wUGT7TgVO:-NNH3RLvAvQksLc5EBUq:b-nax4fv) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/status/registry.go#L106)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

There's no need for this sprintfed-"hash" thing. You can make `struct KV { Key, Value string }` or so, and use this as keys of `children`.
</blockquote></details>

ok, good idea

**Review by krdln — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1257)* status: all files reviewed, 6 unresolved discussions (waiting on @DariaKunoichi)

___
*[`pkg/notifiers/fx-driver.go` line 154 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNGzYJE8y9m7ED2nDqe:-NNH7Hkh2U7ycOY7NI0h:bu85m9z) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/notifiers/fx-driver.go#L154)):*
<details><summary><i>Previously, DariaKunoichi (Daria Bialobrzeska) wrote…</i></summary><blockquote>

ok, so what would you use? ;D
</blockquote></details>

Dunno, "key"?

**Review by DariaKunoichi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1257)* status: all files reviewed, 6 unresolved discussions (waiting on @krdln)

___
*[`pkg/notifiers/fx-driver.go` line 154 at r1](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNGzYJE8y9m7ED2nDqe:-NNH8cMKA3-5F2BhnwUu:b-3rnzk1) ([raw file](https://github.com/fluxninja/aperture/blob/8092389569a2fe8f3d17cf33f318f55cfdc6a280/pkg/notifiers/fx-driver.go#L154)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

Dunno, "key"?
</blockquote></details>

Genious.

**Review by krdln — APPROVED** [review]
Negative diff! :tada: 

> Reviewed 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1257#-:-NNHcCi3AeL22Y72VyPr:bjbjujk)* status: all files reviewed, 1 unresolved discussion (waiting on @DariaKunoichi)

___
*[`pkg/status/registry.go` line 70 at r2](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNHbRPJE25Rl0oWPzHF:-NNHbRPJE25Rl0oWPzHG:b-o92ziu) ([raw file](https://github.com/fluxninja/aperture/blob/14e3d1bb8138ad13b0ebf7260e6e56398f4033d3/pkg/status/registry.go#L70)):*
> ```Go
> func fromString(hash string) kv {
> 	split := strings.Split(hash, ":")
> 	return kv{Key: split[0], Value: split[1]}
> ```

Nit: there's a cool `Cut` function https://pkg.go.dev/strings#Cut
___
*[`pkg/status/registry.go` line 212 at r2](https://reviewable.io/reviews/fluxninja/aperture/1257#-NNHbtwN9SCCJ1PfFQed:-NNHbtwN9SCCJ1PfFQee:bp3czfk) ([raw file](https://github.com/fluxninja/aperture/blob/14e3d1bb8138ad13b0ebf7260e6e56398f4033d3/pkg/status/registry.go#L212)):*
> ```Go
> 		kv := fromString(hash)
> 		r.Child(kv.Key, kv.Value).SetGroupStatus(gs)
> 	}
> ```

I understand that groupstatus will be updated to the new "KV" scheme in subsequent PR

**Pull request merged**
