### PR TITLE
Add FluxNinja Cloud section to docs

### PR DESCRIPTION
**Pull request by DariaKunoichi**
Ref: GH-[5886](https://github.com/fluxninja/cloud/issues/5886)

- - -
This change is [Reviewable](https://reviewable.io/reviews/fluxninja/aperture/252)

### CODE REVIEW

**Review by krdln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/252)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @DariaKunoichi and @krdln)

___
*[`docs/content/cloud/_category_.yml` line 1 at r1](https://reviewable.io/reviews/fluxninja/aperture/252#-NAilFQOB_VQMfN9F67c:-NAilFQOB_VQMfN9F67d:b-p5hlv4) ([raw file](https://github.com/fluxninja/aperture/blob/af3fb403f5f13806db168e1f33a8f2c8e7fa6ee4/docs/content/cloud/_category_.yml#L1)):*
> ```YAML
> label: FluxNinja Cloud
> ```

Perhaps would be nice to have `cloud/cloud.md` to explain what the fluxninja cloud even is?
___
*[`docs/content/cloud/plugin.md` line 13 at r1](https://reviewable.io/reviews/fluxninja/aperture/252#-NAimKH8EWSOLi21hPcE:-NAimKH9EakrhwNN06u_:b-id6tdc) ([raw file](https://github.com/fluxninja/aperture/blob/af3fb403f5f13806db168e1f33a8f2c8e7fa6ee4/docs/content/cloud/plugin.md#L13)):*
> ```Markdown
> If you are also a FluxNinja Cloud user you can enhance your Aperture experience by enabling FluxNinja plugins.
> Plugins provide us with the ability to enrich your logs and traces with additional information.
> It implements Open Telemetry standard and allows us to batch/rollup metrics so that they do not take a lot of bandwidth.
> ```

What does it mean "it implements Open Telemetry standard"?
___
*[`docs/content/cloud/plugin.md` line 14 at r1](https://reviewable.io/reviews/fluxninja/aperture/252#-NAimtbM01IZcbH2h_QQ:-NAimtbM01IZcbH2h_QR:b-59ws33) ([raw file](https://github.com/fluxninja/aperture/blob/af3fb403f5f13806db168e1f33a8f2c8e7fa6ee4/docs/content/cloud/plugin.md#L14)):*
> ```Markdown
> Plugins provide us with the ability to enrich your logs and traces with additional information.
> It implements Open Telemetry standard and allows us to batch/rollup metrics so that they do not take a lot of bandwidth.
> By using them Aperture can make better flow control decisions.
> ```

Isn't the plugin & cloud just for visibility?



_Code quote:_
```Markdown
By using them Aperture can make better flow control decisions.
```
___
*[`docs/content/cloud/plugin.md` line 19 at r1](https://reviewable.io/reviews/fluxninja/aperture/252#-NAim4tEEZQTAg-kGxQp:-NAim4tEEZQTAg-kGxQq:bs8pchz) ([raw file](https://github.com/fluxninja/aperture/blob/af3fb403f5f13806db168e1f33a8f2c8e7fa6ee4/docs/content/cloud/plugin.md#L19)):*
> ```Markdown
> ## Configuration
> 
> If you enable plugins then you can configure for example certificates for a secure connection with FluxNinja cloud or a heartbeats interval.
> ```

Link to plugin configuration reference?
___
*[`docs/content/cloud/plugin.md` line 29 at r1](https://reviewable.io/reviews/fluxninja/aperture/252#-NAimCmGDPdDEoyj7qQL:-NAimCmGDPdDEoyj7qQM:be4ozz9) ([raw file](https://github.com/fluxninja/aperture/blob/af3fb403f5f13806db168e1f33a8f2c8e7fa6ee4/docs/content/cloud/plugin.md#L29)):*
> ```Markdown
>   heartbeat_interval: "10s"
>   client_grpc:
>     insecure: true
> ```

I don't think we should showcase `insecure` in examples :laughing: 
We should showcase actual configuration someone might use.

**Review by DariaKunoichi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/252)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @DariaKunoichi and @krdln)

___
*[`docs/content/cloud/plugin.md` line 13 at r1](https://reviewable.io/reviews/fluxninja/aperture/252#-NAimKH8EWSOLi21hPcE:-NAiouwR1iiROgzkBfnq:bocfzzr) ([raw file](https://github.com/fluxninja/aperture/blob/af3fb403f5f13806db168e1f33a8f2c8e7fa6ee4/docs/content/cloud/plugin.md#L13)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

What does it mean "it implements Open Telemetry standard"?
</blockquote></details>

Plugin is processing logs and traces according to (and using lib) Open Telemetry.
What exactly is "wonky" in this sentence for you? 
___
*[`docs/content/cloud/plugin.md` line 14 at r1](https://reviewable.io/reviews/fluxninja/aperture/252#-NAimtbM01IZcbH2h_QQ:-NAip8lvBv687KJRpRfH:b-zcnu3r) ([raw file](https://github.com/fluxninja/aperture/blob/af3fb403f5f13806db168e1f33a8f2c8e7fa6ee4/docs/content/cloud/plugin.md#L14)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

Isn't the plugin & cloud just for visibility?
</blockquote></details>

okay, I'll reword it
___
*[`docs/content/cloud/plugin.md` line 19 at r1](https://reviewable.io/reviews/fluxninja/aperture/252#-NAim4tEEZQTAg-kGxQp:-NAipB0C6ayS48y1IbpG:b-4gar60) ([raw file](https://github.com/fluxninja/aperture/blob/af3fb403f5f13806db168e1f33a8f2c8e7fa6ee4/docs/content/cloud/plugin.md#L19)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

Link to plugin configuration reference?
</blockquote></details>

ok, will add 
___
*[`docs/content/cloud/plugin.md` line 29 at r1](https://reviewable.io/reviews/fluxninja/aperture/252#-NAimCmGDPdDEoyj7qQL:-NAipDZo7y99UbE88kqm:b-xoud6x) ([raw file](https://github.com/fluxninja/aperture/blob/af3fb403f5f13806db168e1f33a8f2c8e7fa6ee4/docs/content/cloud/plugin.md#L29)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

I don't think we should showcase `insecure` in examples :laughing: 
We should showcase actual configuration someone might use.
</blockquote></details>

haha, you are right, I did not know if I even can post config there ;D

**Review by krdln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/252)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @DariaKunoichi and @krdln)

___
*[`docs/content/cloud/plugin.md` line 13 at r1](https://reviewable.io/reviews/fluxninja/aperture/252#-NAimKH8EWSOLi21hPcE:-NAiuZbf-RhJgKJhelr4:b7f8jea) ([raw file](https://github.com/fluxninja/aperture/blob/af3fb403f5f13806db168e1f33a8f2c8e7fa6ee4/docs/content/cloud/plugin.md#L13)):*
<details><summary><i>Previously, DariaKunoichi (Daria Danilenko) wrote…</i></summary><blockquote>

Plugin is processing logs and traces according to (and using lib) Open Telemetry.
What exactly is "wonky" in this sentence for you? 
</blockquote></details>

Hm, perhaps it's ok :shrug: But Agent without plugin is also processing logs & traces using opentelemetry collector, so it might be misleading... I'm just not sure if mentioning opentelemetry is important here – plugin adds some more aggregations and sends data to cloud prometheus and cloud druid, but usage of opentelemetry is just a middleman that we use to forward data.

**Review by krdln — APPROVED** [review]
Don't forget about adding link to configuration reference.

Also, would be nice for someone working more closely with-plugin to proof-read.

LGTM otherwise!

> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/252#-:-NAj3jng16bjpHeHlx9o:b-e2udkz)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @DariaKunoichi and @krdln)

___
*[`docs/content/cloud/plugin.md` line 19 at r1](https://reviewable.io/reviews/fluxninja/aperture/252#-NAim4tEEZQTAg-kGxQp:-NAj3ROc9TxaawXOd-Ob:b-l073um) ([raw file](https://github.com/fluxninja/aperture/blob/af3fb403f5f13806db168e1f33a8f2c8e7fa6ee4/docs/content/cloud/plugin.md#L19)):*
<details><summary><i>Previously, DariaKunoichi (Daria Danilenko) wrote…</i></summary><blockquote>

ok, will add 
</blockquote></details>

waiting :D

**Pull request merged**
