### PR TITLE
Added details and support for smooth upgrade of aperture

### LINKED ISSUE #970: Document how to upgrade the Controller and Agent installations

### PR DESCRIPTION
**Pull request by hdkshingala**
### Description of change

Helm doesn't upgrade the CRDs when we run the `helm upgrade` command so we need to handle is separately.
Also, when we use `helm template`, the operator controller needs to be in the running state as the CR update will go via the webhook and if the operator is not running, it throws errors. So changed the upgarde strategy for it to RollingUpgrade and added a feature in operator to set the defaults on restart so that the correct defaults are set in the CR.

Fixes #970 

##### Checklist

- [x] Tested in playground or other setup
- [x] Documentation is changed or added

- - -
This change is [Reviewable](https://reviewable.io/reviews/fluxninja/aperture/980)

### CODE REVIEW

**Review by kklimonda-fn — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/980)* status: all files reviewed, 3 unresolved discussions (waiting on @hdkshingala)

___
*[`docs/content/get-started/installation/controller.md` line 38 at r1](https://reviewable.io/reviews/fluxninja/aperture/980#-NICd_Md44gHZZNyt6LF:-NICd_Md44gHZZNyt6LG:bl1zk9j) ([raw file](https://github.com/fluxninja/aperture/blob/f76c70d398c153b897d45b95957c75a1a60238f6/docs/content/get-started/installation/controller.md#L38)):*
> ```Markdown
> [here](/references/configuration/controller.md).
> 
> ## Upgradation {#controller-upgradation}
> ```

I think a more familiar phrase would be "Upgrade procedure" or something similar
___
*[`docs/content/get-started/installation/agent/kubernetes/daemonset.md` line 16 at r1](https://reviewable.io/reviews/fluxninja/aperture/980#-NICdoG14B2tst6QWzOq:-NICdoG14B2tst6QWzOr:buo9nmt) ([raw file](https://github.com/fluxninja/aperture/blob/f76c70d398c153b897d45b95957c75a1a60238f6/docs/content/get-started/installation/agent/kubernetes/daemonset.md#L16)):*
> ```Markdown
> where it will get deployed on all the nodes of the cluster.
> 
> ## Upgradation {#agent-daemonset-upgradation}
> ```

Same here
___
*[`manifests/charts/aperture-controller/values.yaml` line 88 at r1](https://reviewable.io/reviews/fluxninja/aperture/980#-NICdyryCNsO4Rj4i_RE:-NICdyryCNsO4Rj4i_RF:b-zmfrl) ([raw file](https://github.com/fluxninja/aperture/blob/f76c70d398c153b897d45b95957c75a1a60238f6/manifests/charts/aperture-controller/values.yaml#L88)):*
> ```YAML
>   ##  type: Recreate
>   ##
>   updateStrategy:
> ```

@kwapik can you give some input here? From what I remember, aperture-controller is not handling rolling upgrade (where there are two controller pods running at the same time) in a reasonble manner, and that's why we were using Recreate here. Has something changed and we can switch to RollingUpgrade here?

**Review by hdkshingala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/980)* status: all files reviewed, 3 unresolved discussions (waiting on @kwapik)

___
*[`manifests/charts/aperture-controller/values.yaml` line 88 at r1](https://reviewable.io/reviews/fluxninja/aperture/980#-NICdyryCNsO4Rj4i_RE:-NICeWtL1G_6D6B3qI70:b-mnb1wd) ([raw file](https://github.com/fluxninja/aperture/blob/f76c70d398c153b897d45b95957c75a1a60238f6/manifests/charts/aperture-controller/values.yaml#L88)):*
<details><summary><i>Previously, kklimonda-fn (Krzysztof Klimonda) wrote…</i></summary><blockquote>

@kwapik can you give some input here? From what I remember, aperture-controller is not handling rolling upgrade (where there are two controller pods running at the same time) in a reasonble manner, and that's why we were using Recreate here. Has something changed and we can switch to RollingUpgrade here?
</blockquote></details>

@kklimonda-fn This is for the operator controller and not the aperture controller. We need this as when the helm command is executed, it tried to update the CR as well and if the operator controller is not in running state, the webhook fails so we need the operator controller running.

**Review by hdkshingala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/980)* status: 12 of 15 files reviewed, 3 unresolved discussions (waiting on @kklimonda-fn and @kwapik)

___
*[`docs/content/get-started/installation/controller.md` line 38 at r1](https://reviewable.io/reviews/fluxninja/aperture/980#-NICd_Md44gHZZNyt6LF:-NICgV-I2Ejyw42Sp0W1:bvaq17k) ([raw file](https://github.com/fluxninja/aperture/blob/f76c70d398c153b897d45b95957c75a1a60238f6/docs/content/get-started/installation/controller.md#L38)):*
<details><summary><i>Previously, kklimonda-fn (Krzysztof Klimonda) wrote…</i></summary><blockquote>

I think a more familiar phrase would be "Upgrade procedure" or something similar
</blockquote></details>

Updated the title as suggested. Thank you!
___
*[`docs/content/get-started/installation/agent/kubernetes/daemonset.md` line 16 at r1](https://reviewable.io/reviews/fluxninja/aperture/980#-NICdoG14B2tst6QWzOq:-NICgTIW4VFBr9-2mAVc:b-wtgi35) ([raw file](https://github.com/fluxninja/aperture/blob/f76c70d398c153b897d45b95957c75a1a60238f6/docs/content/get-started/installation/agent/kubernetes/daemonset.md#L16)):*
<details><summary><i>Previously, kklimonda-fn (Krzysztof Klimonda) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Updated as suggested.

**Review by kklimonda-fn — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/980#-:-NICj0tL1XTUp9ekvTGr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @hdkshingala)

**Pull request merged**
