### PR TITLE
feat: CI workflow for Helm release 

### PR DESCRIPTION
**Pull request by slayer321**
The PR will help us release the Helm chart as we create the tag for the specific chart.

- - -
This change is [Reviewable](https://reviewable.io/reviews/fluxninja/aperture/327)

### CODE REVIEW

**Comment by slayer321** [comment]
@sbienkow-ninja I tried to add the workflow in the `config.yaml` file  and now pipeline is giving `Max number of workflows exceeded.` .. Is there any workaround for this ?
cc @hdkshingala

**Comment by slayer321** [comment]
Was able to find this [blog](https://support.circleci.com/hc/en-us/articles/360060934851--Max-number-of-workflows-exceeded-error) ... but don't know how can we apply it here .. as we are using `when` field and we cannot use multiple in single workflow

**Review by sbienkow-ninja — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/327)* status: all files reviewed, 2 unresolved discussions (waiting on @slayer321)

___
*[`.circleci/config.yml` line 252 at r2](https://reviewable.io/reviews/fluxninja/aperture/327#-NBH2fDu4afl7p7FJV-M:-NBH2fDu4afl7p7FJV-N:bsfaj2z) ([raw file](https://github.com/fluxninja/aperture/blob/0a3d8293308b4d68b969619980852723002c5391/.circleci/config.yml#L252)):*
> ```YAML
>           filters:
>             tags:
>               only: /^releases/charts/*/v*/
> ```

You'd need to add this job call under `release-components` workflow.



_Code quote:_
```YAML
      - helm-release:
          filters:
            tags:
              only: /^releases/charts/*/v*/
```

**Comment by slayer321** [comment]
In the `release-components` workflow we have the `when` field .. which doesn't match our tag requirement for the chart tag ...
this is what the chart tags will look like 
``` 
releases/charts/aperture-controller/v0.0.1
releases/charts/aperture-agent/v0.0.1
releases/charts/istioconfig/v0.0.1
```

**Review by sbienkow-ninja — COMMENTED** [review]
I wanted to say:
> Yes, but `^releases/(?!aperture-agent).*$` does match all of those, right?
> And is there an issue with having `when` in workflow be more generic, and then having more specific filters per-job lower?
But I see I also did have to split it for some reason.

Perhaps best bet would be to do it properly and extracting all the release workflows to a separate config, and then using https://circleci.com/developer/orbs/orb/circleci/continuation

So in `config.yml` we'd have:
```yaml
[...]
workflows:
    filter-paths-main: {...}
    filter-paths-pr: {...}
    release:
        when:
            matches: { value: << pipeline.git.tag >>, pattern: "^releases/.*$" }
        jobs:
            - contination/continue:
                  configuration_path: .circleci/release.yaml
```

        

> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/327#-:-NBH8ZjjAytQ1hUBO1YU:b6xoqj8)* status: all files reviewed, 2 unresolved discussions (waiting on @slayer321)

**Review by sbienkow-ninja — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/327)* status: all files reviewed, 1 unresolved discussion (waiting on @slayer321)

___
*[`.circleci/config.yml` line 6 at r4](https://reviewable.io/reviews/fluxninja/aperture/327#-NBHKGyo2C-8xiwk0R9D:-NBHKGyo2C-8xiwk0R9E:b-vnfoyt) ([raw file](https://github.com/fluxninja/aperture/blob/bf217257eb7e753abc9710bc4912213058991585/.circleci/config.yml#L6)):*
> ```YAML
> setup: true
> 
> executors:
> ```

I believe all executors, commands and jobs should now be moved to `releases.yaml`



_Code quote:_
```YAML
executors:
  base-cimg-executor:
    docker:
      - image: cimg/base:2021.07
  ubuntu-go-executor:
    docker:
      - image: cimg/go:1.19

# TODO: Sync this with continue-workflows.yml
commands:
  asdf_install:
    description: "Install tools using ASDF"
    parameters:
      tools:
        type: string
        description:
          "Newline separated list of tools to install. If empty, will install
          everything."
        default: ""
      cache_name:
        type: string
        description: "Name of asdf cache"
        default: "default"
    steps:
      - run:
          name: Install ASDF
          command: |
            git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.2
            printf '\nsource "${HOME}/.asdf/asdf.sh"\n' >> "${BASH_ENV}"
            date +%m > ~/month
            date +%d > ~/day
      # We need to restore ASDF cache after installing, otherwise we will try to clone it to non-empty dir
      - restore_cache:
          name: Restore ASDF cache
          keys:
            - aperture-asdf-cache-v7-{{ checksum "~/month" }}-<< parameters.cache_name >>-{{ checksum ".tool-versions" }}-{{ checksum "go.mod" }}
            - aperture-asdf-cache-v7-{{ checksum "~/month" }}-<< parameters.cache_name >>-
      - run:
          name: Install ASDF tools
          environment:
            TOOLS: << parameters.tools >>
          command: .circleci/scripts/asdf_install.sh
  asdf_save_cache:
    parameters:
      cache_name:
        type: string
        description: "Name of asdf cache"
        default: "default"
    steps:
      - save_cache:
          name: Save ASDF cache
          key: aperture-asdf-cache-v7-{{ checksum "~/month" }}-<< parameters.cache_name >>-{{ checksum ".tool-versions" }}-{{ checksum "go.mod" }}
          paths:
            - ~/.asdf
  opsninja_install:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8d:43:0f:09:ed:86:44:23:4f:43:88:29:71:bf:92:e7" # fluxninja/cloud R/O
      - run:
          name: Install opsninja and its dependencies
          command: |
            # We need R/O access to cloud repository to be able to fetch opsninja library
            # FIXME: make "releases" of opsninja library somehow, even as a separate repository
            # to limit exposure.
            export CLOUD_RO_KEY_FINGERPRINT="8d:43:0f:09:ed:86:44:23:4f:43:88:29:71:bf:92:e7"
            export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa_$(echo "${CLOUD_RO_KEY_FINGERPRINT}" | tr -d ':')"
            export SSH_AUTH_SOCK=""
            # Bust asdf cache as our opsninja version is always 0.0.0
            pip uninstall -y opsninja
            pip install 'git+ssh://git@github.com/fluxninja/cloud@main#egg=opsninja&subdirectory=ops/apps/opsninja/'
            asdf reshim

jobs:
  release-components:
    executor: base-cimg-executor
    steps:
      - checkout
      - asdf_install:
          cache_name: release
          tools: |-
            python
            gcloud
      - opsninja_install
      - run:
          name: Schedule release jobs
          working_directory: ops/apps/opsninja
          command: fn circleci trigger-release --tag << pipeline.git.tag >>
      - asdf_save_cache:
          cache_name: release
  package-agent:
    parameters:
      executor:
        type: executor
        description: executor to use for this job
        default:  ubuntu-go-executor
      workspace-name:
        type: string
        description: the name of the workspace to which built packages should be added
        default: packages
      goarch:
        type: string
        description: the GOARCH to use for the build
        default: amd64
    executor: <<parameters.executor>>
    environment:
      PACKAGES_DIR: "/tmp/packages"
      GOARCH: <<parameters.goarch>>
    steps:
      - checkout
      - run:
          name: "Set build vars"
          command: |
            GIT_BRANCH="$(git branch --show-current)"
            GIT_COMMIT_HASH="$(git log -n1 --format=%H)"
            GOOS="$(go env GOOS)"
            VERSION="$(cut -d/ -f3- \<<<"${RELEASE_TAG}")"
            if which dpkg; then
              PACKAGER=deb
            elif which rpm; then
              PACKAGER=rpm
            elif which apk; then
              PACKAGER=apk
            else
              echo "Unable to determine proper packager for current OS"
              exit 1
            fi

            export GIT_BRANCH GIT_COMMIT_HASH GOOS VERSION PACKAGER
            declare -p GIT_BRANCH GIT_COMMIT_HASH GOOS VERSION PACKAGER >> "${BASH_ENV}"
          environment:
            RELEASE_TAG: <<pipeline.git.tag>>
      - run:
          name: "Compile agent and plugins"
          command: |
            SOURCE="./cmd/aperture-agent" TARGET="./dist/aperture-agent" ./pkg/info/build.sh
            for plugin_dir in ./plugins/*/aperture-plugin-*; do
              plugin="$(basename "${plugin_dir}")"
              echo "Building plugin ${plugin}"
              SOURCE="${plugin_dir}" TARGET="./dist/plugins/${plugin}.so" ./pkg/plugins/build.sh
            done
          environment:
            CGO_ENABLED: "1"
            PREFIX: "aperture"
            LDFLAGS: "-s -w"
      - run:
          name: Install nFPM
          command: |
            filename="nfpm_amd64.${PACKAGER}"
            file="/tmp/${filename}"
            curl --silent --show-error --location https://github.com/goreleaser/nfpm/releases/latest/download/${filename} -o "${file}"
            case "${PACKAGER}" in
              deb) sudo dpkg -i "${file}";;
              rpm) sudo rpm -i "${file}";;
              apk) sudo apk add --allow-untrusted "${file}";;
              *) echo "Unknown packager ${PACKAGER}"; exit 1;;
            esac
            which nfpm
      - run:
          name: Package
          command: |
            mkdir -p dist/packages/
            nfpm package --packager "${PACKAGER}" --target dist/packages/
            ls -l dist/packages/
  helm-release:
    executor: base-cimg-executor
    steps:
      - checkout
      - run:
          name: "Package and release Helm Chart"
          command: .circleci/scripts/helm_release.sh
```

**Review by sbienkow-ninja — COMMENTED** [review]
And orbs, it also needs the orbs to be defined in order to use them in workflows :)

> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/327#-:-NBHNOsf7f1GgRKmxGas:b-z5cjfy)* status: all files reviewed, 1 unresolved discussion (waiting on @slayer321)

**Comment by slayer321** [comment]
Yeah, Cool.. Will add it

**Comment by slayer321** [comment]
When I tried to run `circleci config validate release.yaml` .. got this error
```
Error: All Workflows have been filtered from this Pipeline.
No Jobs have been run.
```

I think this is expected right ? as we have filters in all the workflows

**Review by sbienkow-ninja — CHANGES_REQUESTED** [review]
Yes, that seems right. Unfortunately we can't really do anything about it AFAIK

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/327#-:-NBHUmiM03ShEm-pl6ke:bj5lrbb)* status: all files reviewed, 1 unresolved discussion (waiting on @slayer321)

___
*[`.circleci/releases.yaml` line 4 at r5](https://reviewable.io/reviews/fluxninja/aperture/327#-NBHRWclAmKtkR-XaM4e:-NBHRWclAmKtkR-XaM4f:b-ekuq8w) ([raw file](https://github.com/fluxninja/aperture/blob/b7a937d6420c1410ad05e4c1f494a798ae07175c/.circleci/releases.yaml#L4)):*
> ```YAML
> 
> # this allows to use CircleCI's dynamic configuration feature
> setup: true
> ```

This is only to be used by the `config.yml` - this file is not a setup config.



_Code quote:_
```YAML
# this allows to use CircleCI's dynamic configuration feature
setup: true
```

**Review by sbienkow-ninja — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/327#-:-NBHhNs41b2NrfqR0Z4i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @slayer321)

**Pull request merged**
