### PR TITLE
Add Control Point Type to OLAP telemetry

### PR DESCRIPTION
**Pull request by DariaKunoichi**
### Description of change
Closes: GH-1093

##### Checklist

- [x] Tested in playground or other setup
- [ ] Screenshot (Grafana) from playground added to PR for 15+ minute run
- [ ] Documentation is changed or added
- [x] Tests and/or benchmarks are included
- [ ] Breaking changes

- - -
This change is [Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1213)

### CODE REVIEW

**Review by krdln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1213)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @DariaKunoichi)

___
*[`pkg/otelcollector/consts/consts.go` line 9 at r1](https://reviewable.io/reviews/fluxninja/aperture/1213#-NN2BLf4DH6TCjbejSrf:-NN2BLf4DH6TCjbejSrg:b2xn8eq) ([raw file](https://github.com/fluxninja/aperture/blob/565bede4e51e2064543835218e2179a5537e7af1/pkg/otelcollector/consts/consts.go#L9)):*
> ```Go
> 	FEATURE controlPointType = iota
> 	// HTTP is a control point type for envoy authz calls.
> 	HTTP
> ```

Nit: be more descriptive in names: FeatureControlPoint / HTTPControlPoint



_Code quote:_
```Go
	// FEATURE is a default control point type added on Check call.
	FEATURE controlPointType = iota
	// HTTP is a control point type for envoy authz calls.
	HTTP
```
___
*[`pkg/policies/flowcontrol/service/check/check.go` line 72 at r1](https://reviewable.io/reviews/fluxninja/aperture/1213#-NN2BfISCH-eFg2S5ppK:-NN2BfISCH-eFg2S5ppL:bcqeu6r) ([raw file](https://github.com/fluxninja/aperture/blob/565bede4e51e2064543835218e2179a5537e7af1/pkg/policies/flowcontrol/service/check/check.go#L72)):*
> ```Go
> 		labels = make(map[string]string)
> 	}
> 	labels[otelconsts.ApertureControlPointTypeLabel] = fmt.Sprint(otelconsts.FEATURE)
> ```

Nit: `string(otelconst.FEATURE)`, no need to go through fmt.



_Code quote:_
```Go
fmt.Sprint(otelconsts.FEATURE)
```
___
*[`pkg/policies/flowcontrol/service/check/check.go` line 72 at r1](https://reviewable.io/reviews/fluxninja/aperture/1213#-NN2EHJoDwyTzHPjttGg:-NN2EHJoDwyTzHPjttGh:b9hzjq0) ([raw file](https://github.com/fluxninja/aperture/blob/565bede4e51e2064543835218e2179a5537e7af1/pkg/policies/flowcontrol/service/check/check.go#L72)):*
> ```Go
> 		labels = make(map[string]string)
> 	}
> 	labels[otelconsts.ApertureControlPointTypeLabel] = fmt.Sprint(otelconsts.FEATURE)
> ```

(as discussed offline) Not sure if this propagation will be enough for the label to appear on sdk path.

**Review by krdln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1213)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @DariaKunoichi)

___
*[`pkg/policies/flowcontrol/service/check/check.go` line 72 at r1](https://reviewable.io/reviews/fluxninja/aperture/1213#-NN2BfISCH-eFg2S5ppK:-NN2F2ZKBLmQGaBxm14_:b-65al1y) ([raw file](https://github.com/fluxninja/aperture/blob/565bede4e51e2064543835218e2179a5537e7af1/pkg/policies/flowcontrol/service/check/check.go#L72)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

Nit: `string(otelconst.FEATURE)`, no need to go through fmt.
</blockquote></details>

Oh, they're ints! My bad. Does this mean we're putting them as `0`/`1`?

**Review by DariaKunoichi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1213)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @DariaKunoichi and @krdln)

___
*[`pkg/otelcollector/consts/consts.go` line 9 at r1](https://reviewable.io/reviews/fluxninja/aperture/1213#-NN2BLf4DH6TCjbejSrf:-NN3XhPP10jjF6DJiAud:b32w1t) ([raw file](https://github.com/fluxninja/aperture/blob/565bede4e51e2064543835218e2179a5537e7af1/pkg/otelcollector/consts/consts.go#L9)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

Nit: be more descriptive in names: FeatureControlPoint / HTTPControlPoint
</blockquote></details>

Ok
___
*[`pkg/policies/flowcontrol/service/check/check.go` line 72 at r1](https://reviewable.io/reviews/fluxninja/aperture/1213#-NN2EHJoDwyTzHPjttGg:-NN3XVfp-_x8PjQelpS5:bkejwyp) ([raw file](https://github.com/fluxninja/aperture/blob/565bede4e51e2064543835218e2179a5537e7af1/pkg/policies/flowcontrol/service/check/check.go#L72)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

(as discussed offline) Not sure if this propagation will be enough for the label to appear on sdk path.
</blockquote></details>

TelemetryFlowLabels were not set at all in the SDK flow so I added it same way as in authz - after the CheckWithValues
___
*[`pkg/policies/flowcontrol/service/check/check.go` line 72 at r1](https://reviewable.io/reviews/fluxninja/aperture/1213#-NN2BfISCH-eFg2S5ppK:-NN3Xe444CMXun6g6LfW:b-dwxfqo) ([raw file](https://github.com/fluxninja/aperture/blob/565bede4e51e2064543835218e2179a5537e7af1/pkg/policies/flowcontrol/service/check/check.go#L72)):*
<details><summary><i>Previously, krdln (Michał Krasnoborski) wrote…</i></summary><blockquote>

Oh, they're ints! My bad. Does this mean we're putting them as `0`/`1`?
</blockquote></details>

Changed them to Strings

**Review by tanveergill — APPROVED** [review]

**Review by krdln — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/1213)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @DariaKunoichi)

**Pull request merged**
